# -*- coding: utf-8 -*-
"""Classification Codes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lDqSL1Yy7eu0q1e0GcfaI7LeAnHDxG6
"""

# ============================================================
# TASK 1: Basic CNN Implementation (TensorFlow/Keras)
# Build a simple CNN from scratch for cats vs dogs classification
# ============================================================

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import torchvision
from torchvision import datasets, transforms
import os
import zipfile
import urllib.request
from PIL import Image
import warnings
warnings.filterwarnings('ignore')

print("=" * 60)
print("TASK 1: Basic CNN Implementation (TensorFlow/Keras)")
print("=" * 60)

# Download and prepare dataset
print("\nDownloading Cats vs Dogs dataset...")

# Create dataset directory
os.makedirs('dataset', exist_ok=True)

# Download a small subset of cats and dogs dataset (using TensorFlow dataset)
import tensorflow_datasets as tfds

# Load cats vs dogs dataset from tensorflow datasets
print("Loading dataset from TensorFlow Datasets...")
(ds_train, ds_test), ds_info = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:90%]'],  # Use 80% for training, 10% for testing
    shuffle_files=True,
    as_supervised=True,
    with_info=True
)

print(f"Dataset info: {ds_info}")
print(f"Number of training samples: {tf.data.experimental.cardinality(ds_train).numpy()}")
print(f"Number of test samples: {tf.data.experimental.cardinality(ds_test).numpy()}")

# Preprocessing function
def preprocess_image(image, label):
    # Resize images to 64x64
    image = tf.image.resize(image, (64, 64))
    # Normalize pixel values to [0,1]
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

# Prepare the datasets
batch_size = 32
train_dataset = ds_train.map(preprocess_image).batch(batch_size).prefetch(tf.data.AUTOTUNE)
test_dataset = ds_test.map(preprocess_image).batch(batch_size).prefetch(tf.data.AUTOTUNE)

print("\n✓ Dataset loaded and preprocessed successfully!")

# Building the CNN
print("\nBuilding Basic CNN Model...")

basic_cnn = tf.keras.models.Sequential([
    # Convolution + Pooling layers
    tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64, 64, 3]),
    tf.keras.layers.MaxPool2D(pool_size=2, strides=2),

    # Second convolutional layer
    tf.keras.layers.Conv2D(filters=64, kernel_size=3, activation='relu'),
    tf.keras.layers.MaxPool2D(pool_size=2, strides=2),

    # Third convolutional layer
    tf.keras.layers.Conv2D(filters=128, kernel_size=3, activation='relu'),
    tf.keras.layers.MaxPool2D(pool_size=2, strides=2),

    # Flattening
    tf.keras.layers.Flatten(),

    # Full Connection
    tf.keras.layers.Dense(units=256, activation='relu'),
    tf.keras.layers.Dropout(0.5),

    # Output Layer
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

# Compile the model
basic_cnn.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

print("\nBasic CNN Model Summary:")
basic_cnn.summary()

# Train the model (with fewer epochs for demonstration)
print("\nTraining Basic CNN Model (5 epochs for demonstration)...")
history = basic_cnn.fit(
    train_dataset,
    validation_data=test_dataset,
    epochs=1,
    verbose=1
)

print("\n✓ Task 1 Complete: Basic CNN trained successfully!")
print(f"Final Training Accuracy: {history.history['accuracy'][-1]:.4f}")
print(f"Final Validation Accuracy: {history.history['val_accuracy'][-1]:.4f}")

# Plot training history
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.tight_layout()
plt.show()

print("\n" + "=" * 60)
print("TASK 2: Transfer Learning with Pretrained CNN (MobileNetV2)")
print("=" * 60)

# ============================================================
# TASK 2: Transfer Learning with Pretrained Model
# Using MobileNetV2 pretrained on ImageNet for cats vs dogs classification
# ============================================================

print("\nBuilding Transfer Learning Model with MobileNetV2...")

# Load pretrained MobileNetV2 model (without top layers)
pretrained_base = tf.keras.applications.MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(64, 64, 3)
)

# Freeze the pretrained layers
pretrained_base.trainable = False

# Build the model
transfer_cnn = tf.keras.models.Sequential([
    pretrained_base,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(1, activation='sigmoid')
])

# Compile the model
transfer_cnn.compile(optimizer='adam',
                     loss='binary_crossentropy',
                     metrics=['accuracy'])

print("\nTransfer Learning Model Summary:")
transfer_cnn.summary()

# Train the transfer learning model
print("\nTraining Transfer Learning Model (5 epochs for demonstration)...")
history_transfer = transfer_cnn.fit(
    train_dataset,
    validation_data=test_dataset,
    epochs=1,
    verbose=1
)

print("\n✓ Task 2 Complete: Transfer Learning model trained successfully!")
print(f"Final Training Accuracy: {history_transfer.history['accuracy'][-1]:.4f}")
print(f"Final Validation Accuracy: {history_transfer.history['val_accuracy'][-1]:.4f}")

print("\n" + "=" * 60)
print("TASK 3: PyTorch CNN Implementation")
print("=" * 60)

# ============================================================
# TASK 3: PyTorch CNN Implementation
# Building a CNN using PyTorch for cats vs dogs classification
# ============================================================

print("\nBuilding PyTorch CNN Model...")

# Custom Dataset class for Cats vs Dogs
class CatsDogsDataset(Dataset):
    def __init__(self, tf_dataset, transform=None):
        self.tf_dataset = list(tf_dataset)
        self.transform = transform

    def __len__(self):
        return len(self.tf_dataset)

    def __getitem__(self, idx):
        image, label = self.tf_dataset[idx]
        # Convert tensorflow tensor to numpy and then to PIL
        image_np = (image.numpy() * 255).astype(np.uint8)
        image_pil = Image.fromarray(image_np)

        if self.transform:
            image_pil = self.transform(image_pil)

        # Fix: Convert TensorFlow scalar tensor to a Python scalar before creating PyTorch tensor
        return image_pil, torch.tensor(label.numpy(), dtype=torch.float32)

# Define transforms for PyTorch
transform = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Create PyTorch datasets
print("Converting dataset to PyTorch format...")

# Get a small subset for demonstration (first 1000 training and 200 test samples)
train_subset = list(train_dataset.take(32))  # Take 32 batches
test_subset = list(test_dataset.take(10))     # Take 10 batches

# Flatten batches
train_samples = []
for batch_images, batch_labels in train_subset:
    for img, lbl in zip(batch_images, batch_labels):
        train_samples.append((img, lbl))
        if len(train_samples) >= 500:  # Limit to 500 samples for demonstration
            break
    if len(train_samples) >= 500:
        break

test_samples = []
for batch_images, batch_labels in test_subset:
    for img, lbl in zip(batch_images, batch_labels):
        test_samples.append((img, lbl))
        if len(test_samples) >= 100:  # Limit to 100 samples for demonstration
            break
    if len(test_samples) >= 100:
        break

# Create datasets
train_dataset_pytorch = CatsDogsDataset(train_samples, transform=transform)
test_dataset_pytorch = CatsDogsDataset(test_samples, transform=transform)

train_loader = DataLoader(train_dataset_pytorch, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset_pytorch, batch_size=32, shuffle=False)

print(f"PyTorch dataset created with {len(train_dataset_pytorch)} training and {len(test_dataset_pytorch)} test samples")

# Define the CNN class
class CatDogCNN(nn.Module):
    def __init__(self):
        super(CatDogCNN, self).__init__()
        # Convolutional layers
        self.conv_layers = nn.Sequential(
            # First conv block
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            # Second conv block
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            # Third conv block
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
        )

        # Calculate the size after convolutions (for 64x64 input)
        # After 3 MaxPool2d(2,2): 64 -> 32 -> 16 -> 8
        self.fc_input_size = 128 * 8 * 8

        # Fully connected layers
        self.fc_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(self.fc_input_size, 256),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(256, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.conv_layers(x)
        x = self.fc_layers(x)
        return x

# Create model instance
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
pytorch_cnn = CatDogCNN().to(device)
print(f"\nPyTorch CNN Architecture:")
print(f"Model created on device: {device}")

# Define loss function and optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(pytorch_cnn.parameters(), lr=0.001)

print("\nTraining PyTorch CNN (3 epochs for demonstration)...")

# Training loop
train_losses = []
test_accuracies = []

for epoch in range(1):  # 3 epochs for demonstration
    # Training phase
    pytorch_cnn.train()
    running_loss = 0.0
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        # Forward pass
        outputs = pytorch_cnn(images)
        loss = criterion(outputs, labels.view(-1, 1))

        # Backward pass and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    avg_loss = running_loss / len(train_loader)
    train_losses.append(avg_loss)

    # Validation phase
    pytorch_cnn.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = pytorch_cnn(images)
            predicted = (outputs > 0.5).float()
            total += labels.size(0)
            correct += (predicted.view(-1) == labels).sum().item()

    accuracy = 100 * correct / total
    test_accuracies.append(accuracy)

    print(f'Epoch [{epoch+1}/3], Loss: {avg_loss:.4f}, Validation Accuracy: {accuracy:.2f}%')

print("\n✓ Task 3 Complete: PyTorch CNN trained successfully!")

print("\n" + "=" * 60)
print("SUMMARY OF THREE TASKS COMPLETED")
print("=" * 60)
print("✓ Task 1: Basic CNN from scratch using TensorFlow/Keras")
print(f"   - Final Validation Accuracy: {history.history['val_accuracy'][-1]:.4f}")
print("✓ Task 2: Transfer Learning with MobileNetV2")
print(f"   - Final Validation Accuracy: {history_transfer.history['val_accuracy'][-1]:.4f}")
print("✓ Task 3: PyTorch CNN Implementation")
print(f"   - Final Validation Accuracy: {test_accuracies[-1]:.2f}%")
print("\nAll three models have been successfully trained on the Cats vs Dogs dataset!")
print("Note: Training was done with limited epochs for demonstration purposes.")