# -*- coding: utf-8 -*-
"""CVLab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5xHXH-FQmZjPqHYKa8PJzVfViOzCPEC
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.util import random_noise
def show(img, title=""):
  plt.figure(figsize=(4,4))
  plt.imshow(img, cmap='gray')
  plt.title(title)
  plt.axis('off')

"""ASSIGNMENT 1"""

img = cv2.imread('img.png', 0) / 255.0
noisy = random_noise(img, mode='gaussian', mean=0, var=0.05)
noisy = (noisy * 255).astype(np.uint8)
filtered = cv2.blur(noisy, (5,5))
show(img, "Original")
show(noisy, "Gaussian Noise")
show(filtered, "Arithmetic Mean Filter")

"""ASSIGNMENT 2"""

def geometric_mean_filter(img, k=3):
  img = img.astype(np.float32) + 1
  kernel = np.ones((k,k))
  log_img = np.log(img)
  filtered = cv2.filter2D(log_img, -1, kernel)
  return np.exp(filtered / (k*k)).astype(np.uint8)
filtered = geometric_mean_filter(noisy, 3)
show(noisy, "Gaussian Noise")
show(filtered, "Geometric Mean Filter")

"""ASSIGNMENT 3"""

def harmonic_mean_filter(img, k=3):
  img = img.astype(np.float32)
  kernel = np.ones((k,k))
  denom = cv2.filter2D(1.0 / (img + 1e-6), -1, kernel)
  return ((k*k) / denom).astype(np.uint8)
salt = random_noise(img, mode='salt', amount=0.1)
salt = (salt * 255).astype(np.uint8)
filtered = harmonic_mean_filter(salt, 3)

show(salt, "Salt Noise")
show(filtered, "Harmonic Mean Filter")

"""ASSIGNMENT 4"""

def contraharmonic_mean(img, k=3, Q=1.5):
  img = img.astype(np.float32)
  kernel = np.ones((k,k))
  num = cv2.filter2D(img**(Q+1), -1, kernel)
  den = cv2.filter2D(img**Q + 1e-6, -1, kernel)
  return (num / den).astype(np.uint8)
pepper = random_noise(img, mode='pepper', amount=0.1)
pepper = (pepper * 255).astype(np.uint8)
filtered = contraharmonic_mean(pepper, 3, Q=1.5)
show(pepper, "Pepper Noise")
show(filtered, "Contraharmonic Mean Filter")

"""ASSIGNMENT 5"""

sp = random_noise(img, mode='s&p', amount=0.2)
sp = (sp * 255).astype(np.uint8)
filtered = cv2.medianBlur(sp, 5)
show(sp, "Salt & Pepper Noise")
show(filtered, "Median Filter")

"""ASSIGNMENT 6"""

sp_noise = random_noise(img, mode='s&p', amount=0.2)
sp_noise = (sp_noise * 255).astype(np.uint8)

min_filtered = cv2.erode(sp_noise, np.ones((3,3), np.uint8), iterations=1)

max_filtered = cv2.dilate(sp_noise, np.ones((3,3), np.uint8), iterations=1)

show(sp_noise, "Salt & Pepper Noise")
show(min_filtered, "Min Filter")
show(max_filtered, "Max Filter")

"""ASSIGNMENT 7"""

gaussian_noise = random_noise(img, mode='gaussian', mean=0, var=0.05)
gaussian_noise = (gaussian_noise * 255).astype(np.uint8)

mixed_noisy_image = random_noise(gaussian_noise / 255.0, mode='s&p', amount=0.1)
mixed_noisy_image = (mixed_noisy_image * 255).astype(np.uint8)

show(img, "Original Image")
show(mixed_noisy_image, "Mixed Noise (Gaussian + S&P)")

def alpha_trimmed_mean_filter(img, k=3, d=2):
  img = img.astype(np.float32)
  rows, cols = img.shape
  filtered_img = np.zeros_like(img)

  pad = k // 2

  for i in range(pad, rows - pad):
    for j in range(pad, cols - pad):
      window = img[i - pad:i + pad + 1, j - pad:j + pad + 1].flatten()
      sorted_window = np.sort(window)
      trim_count = int(d / 2)
      trimmed_window = sorted_window[trim_count : len(sorted_window) - trim_count]
      filtered_img[i, j] = np.mean(trimmed_window)

  return filtered_img.astype(np.uint8)

alpha_trimmed_filtered = alpha_trimmed_mean_filter(mixed_noisy_image, k=5, d=4)

show(alpha_trimmed_filtered, "Alpha-Trimmed Mean Filter (d=4)")

arithmetic_mean_filtered = cv2.blur(mixed_noisy_image, (5,5))
median_filtered = cv2.medianBlur(mixed_noisy_image, 5)

show(arithmetic_mean_filtered, "Arithmetic Mean Filter")
show(median_filtered, "Median Filter")

"""ASSIGNMENT 8"""

img_float = img.astype(np.float64)

rows, cols = img.shape
variance_map = np.zeros_like(img_float)

for j in range(cols):
  variance_map[:, j] = 0.01 + (0.09 * (j / (cols - 1)))

spatially_noisy_image = random_noise(img_float, mode='gaussian', var=variance_map)
spatially_noisy_image = (spatially_noisy_image * 255).astype(np.uint8)

show(img, "Original Image")
show(spatially_noisy_image, "Spatially Varying Gaussian Noise")

def adaptive_local_noise_reduction_filter(img, global_noise_variance, ksize=7):
    img_float = img.astype(np.float32)
    rows, cols = img.shape
    filtered_img = np.zeros_like(img_float)

    pad = ksize // 2

    for i in range(pad, rows - pad):
        for j in range(pad, cols - pad):
            window = img_float[i - pad : i + pad + 1, j - pad : j + pad + 1]
            local_mean = np.mean(window)
            local_variance = np.var(window)
            if local_variance < global_noise_variance:
                weight = local_variance / (global_noise_variance + 1e-6)
            else:
                weight = global_noise_variance / (local_variance + 1e-6)

            filtered_img[i, j] = img_float[i, j] - (weight * (img_float[i, j] - local_mean))

    filtered_img = np.clip(filtered_img, 0, 255).astype(np.uint8)
    return filtered_img

global_noise_variance_estimate = np.mean(variance_map) * (255**2)

adaptive_filtered_image = adaptive_local_noise_reduction_filter(spatially_noisy_image,
                                                                global_noise_variance=global_noise_variance_estimate,
                                                                ksize=7)
arithmetic_mean_filtered = cv2.blur(mixed_noisy_image, (5,5))
show(adaptive_filtered_image, "Adaptive Local Noise Reduction Filter")
show(arithmetic_mean_filtered, "Arithmetic Mean Filter")

"""ASSIGNMENT 9"""

sp_noisy_image = random_noise(img, mode='s&p', amount=0.1)
sp_noisy_image = (sp_noisy_image * 255).astype(np.uint8)
show(img, "Original Image")
show(sp_noisy_image, "Salt & Pepper Noisy Image")

filtered_3x3 = cv2.medianBlur(sp_noisy_image, 3)
filtered_5x5 = cv2.medianBlur(sp_noisy_image, 5)
filtered_7x7 = cv2.medianBlur(sp_noisy_image, 7)

show(filtered_3x3, "Median Filter (3x3)")
show(filtered_5x5, "Median Filter (5x5)")
show(filtered_7x7, "Median Filter (7x7)")

original_img_uint8 = (img * 255).astype(np.uint8)

def calculate_psnr(original, compressed):
  mse = np.mean((original - compressed)**2)
  if mse == 0:
    return 100
  max_pixel = 255.0
  psnr = 20 * np.log10(max_pixel / np.sqrt(mse))
  return psnr

psnr_noisy = calculate_psnr(original_img_uint8, sp_noisy_image)
psnr_3x3 = calculate_psnr(original_img_uint8, filtered_3x3)
psnr_5x5 = calculate_psnr(original_img_uint8, filtered_5x5)
psnr_7x7 = calculate_psnr(original_img_uint8, filtered_7x7)

psnr_values = [psnr_noisy, psnr_3x3, psnr_5x5, psnr_7x7]
window_sizes = ['Noisy', '3x3', '5x5', '7x7']

print(f"PSNR of Noisy Image: {psnr_noisy:.2f} dB")
print(f"PSNR of 3x3 Filtered Image: {psnr_3x3:.2f} dB")
print(f"PSNR of 5x5 Filtered Image: {psnr_5x5:.2f} dB")
print(f"PSNR of 7x7 Filtered Image: {psnr_7x7:.2f} dB")

plt.figure(figsize=(8, 6))
plt.plot(window_sizes, psnr_values, marker='o', linestyle='-', color='b')
plt.title('PSNR vs. Median Filter Window Size')
plt.xlabel('Filter Window Size')
plt.ylabel('PSNR (dB)')
plt.grid(True)
plt.show()

"""ASSIGNMENT 10"""

gaussian_noise_img = random_noise(img, mode='gaussian', mean=0, var=0.03)
mixed_noisy_image = random_noise(gaussian_noise_img, mode='s&p', amount=0.05)
mixed_noisy_image = (mixed_noisy_image * 255).astype(np.uint8)

def detect_noise_type(image):
    hist = cv2.calcHist([image], [0], None, [256], [0, 256])
    total_pixels = image.size
    zero_pixels = hist[0][0]
    max_pixels = hist[255][0]
    zero_percentage = zero_pixels / total_pixels
    max_percentage = max_pixels / total_pixels
    if zero_percentage > 0.02 and max_percentage > 0.02:
        return 'salt_pepper'
    elif zero_percentage > 0.02:
        return 'pepper'
    elif max_percentage > 0.02:
        return 'salt'
    else:
        return 'gaussian'

def apply_automatic_filter(image):
    noise_type = detect_noise_type(image)
    ksize = 5
    filtered_image = image.copy()
    filter_name = ""

    if noise_type == 'salt_pepper':
        filtered_image = cv2.medianBlur(image, ksize)
        filter_name = "Median Filter (Salt & Pepper)"
    elif noise_type == 'salt':
        filtered_image = contraharmonic_mean(image, k=ksize, Q=1.5)
        filter_name = "Contraharmonic Mean Filter (Salt)"
    elif noise_type == 'pepper':
        filtered_image = contraharmonic_mean(image, k=ksize, Q=-1.5)
        filter_name = "Contraharmonic Mean Filter (Pepper)"
    else:
        filtered_image = cv2.blur(image, (ksize, ksize))
        filter_name = "Arithmetic Mean Filter (Gaussian)"

    return filtered_image, filter_name

auto_filtered_image, applied_filter_name = apply_automatic_filter(mixed_noisy_image)

show(img, "Original Image")
show(mixed_noisy_image, "Mixed Noisy Image (Gaussian + S&P)")
show(auto_filtered_image, applied_filter_name)

