# -*- coding: utf-8 -*-
"""CVLab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m2HAQtBcwZgejZZvzm4rG1zl8OLAg5YO

ASSIGNMENT 1
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

grayscale_natural_img_path = 'grayscale_image_new.jpg'
low_light_img_path = 'low_light_image.jpg'
high_contrast_img_path = 'high_contrast_image.jpg'

gray_image = cv2.imread(grayscale_natural_img_path)
low_light_image_gray = cv2.imread(low_light_img_path)
high_contrast_image_gray = cv2.imread(high_contrast_img_path)

gray_image_negative = 255 - gray_image
low_light_image_negative = 255 - low_light_image_gray
high_contrast_image_negative = 255 - high_contrast_image_gray

plt.figure(figsize=(12, 10))

plt.subplot(3, 2, 1)
plt.imshow(gray_image, cmap='gray')
plt.title('Original Grayscale')
plt.axis('off')

plt.subplot(3, 2, 2)
plt.imshow(gray_image_negative, cmap='gray')
plt.title('Negative Grayscale')
plt.axis('off')

plt.subplot(3, 2, 3)
plt.imshow(low_light_image_gray, cmap='gray')
plt.title('Original Low-Light')
plt.axis('off')

plt.subplot(3, 2, 4)
plt.imshow(low_light_image_negative, cmap='gray')
plt.title('Negative Low-Light')
plt.axis('off')

plt.subplot(3, 2, 5)
plt.imshow(high_contrast_image_gray, cmap='gray')
plt.title('Original High-Contrast')
plt.axis('off')

plt.subplot(3, 2, 6)
plt.imshow(high_contrast_image_negative, cmap='gray')
plt.title('Negative High-Contrast')
plt.axis('off')

plt.show()

def plot_histogram(image, title, ax):
    hist = cv2.calcHist([image], [0], None, [256], [0, 256])
    ax.plot(hist)
    ax.set_title(title)
    ax.set_xlabel('Pixel Intensity')
    ax.set_ylabel('Frequency')

plt.figure(figsize=(15, 12))

ax1 = plt.subplot(3, 2, 1)
plot_histogram(gray_image, 'Histogram - Original Grayscale', ax1)

ax2 = plt.subplot(3, 2, 2)
plot_histogram(gray_image_negative, 'Histogram - Negative Grayscale', ax2)

ax3 = plt.subplot(3, 2, 3)
plot_histogram(low_light_image_gray, 'Histogram - Original Low-Light', ax3)

ax4 = plt.subplot(3, 2, 4)
plot_histogram(low_light_image_negative, 'Histogram - Negative Low-Light', ax4)

ax5 = plt.subplot(3, 2, 5)
plot_histogram(high_contrast_image_gray, 'Histogram - Original High-Contrast', ax5)

ax6 = plt.subplot(3, 2, 6)
plot_histogram(high_contrast_image_negative, 'Histogram - Negative High-Contrast', ax6)

plt.tight_layout()
plt.show()

"""1.  **What happens to the histogram after negation?**
    The histogram of a negative image is an inverted version of the original image's histogram, mirrored around the center of the intensity range (approximately 127.5 for an 8-bit image). Low pixel intensities (dark areas) in the original image correspond to high pixel intensities (bright areas) in the negative image, and vice-versa. The overall shape and distribution of pixel frequencies are preserved but shifted across the intensity spectrum.
2.  **What types of images is negative transformation useful for?**
    Negative transformation is particularly useful for:
    *   **Low-light or underexposed images**: It enhances the visibility of details by converting dark regions into brighter ones.
    *   **Medical imaging (e.g., X-rays)**: It can aid diagnostic visualization by inverting structures (e.g., bone structures appearing black on a white background).

ASSIGNMENT 2
"""



dark_img_path = 'dark.jpg'
bright_img_path = 'bright.jpg'

dark_image = cv2.imread(dark_img_path)
bright_image = cv2.imread(bright_img_path)

def log_transform(image, c):
    image_float = image.astype(np.float32)
    transformed_image = c * np.log(1 + image_float)
    transformed_image = cv2.normalize(transformed_image, None, 0, 255, cv2.NORM_MINMAX)
    return transformed_image.astype(np.uint8)

c_values = [10, 30, 60]

total_images_to_plot = 2 + (2 * len(c_values))

plt.figure(figsize=(15, total_images_to_plot * 2))

plot_index = 1

plt.subplot(int(total_images_to_plot / 2), 2, plot_index)
plt.imshow(dark_image, cmap='gray')
plt.title('Original Dark Image')
plt.axis('off')
plot_index += 1

for c in c_values:
    transformed_dark_image = log_transform(dark_image, c)

    plt.subplot(int(total_images_to_plot / 2), 2, plot_index)
    plt.imshow(transformed_dark_image, cmap='gray')
    plt.title(f'Dark Image after Log Transform (c={c})')
    plt.axis('off')
    plot_index += 1

plt.subplot(int(total_images_to_plot / 2), 2, plot_index)
plt.imshow(bright_image, cmap='gray')
plt.title('Original Bright Image')
plt.axis('off')
plot_index += 1

for c in c_values:
    transformed_bright_image = log_transform(bright_image, c)

    plt.subplot(int(total_images_to_plot / 2), 2, plot_index)
    plt.imshow(transformed_bright_image, cmap='gray')
    plt.title(f'Bright Image after Log Transform (c={c})')
    plt.axis('off')
    plot_index += 1

plt.tight_layout()
plt.show()

"""### Questions:

1.  **Why does log transformation enhance dark regions?**

    Log transformation is defined by the formula `s = c * log(1 + r)`. The logarithmic function has a characteristic curve: it expands the range of small `r` values more significantly than it does for large `r` values. This means that:
    *   Small changes in dark pixel intensities (low `r` values) result in larger changes in output intensities (`s`). This effectively spreads out the pixel values in the darker regions, making distinctions between previously indistinguishable dark shades more apparent, thereby enhancing details in those areas.

2.  **What happens if c is too large?**

    The constant `c` in the log transformation `s = c * log(1 + r)` acts as a scaling factor. If `c` is too large:
    *   **Increased Brightness and Loss of Detail**
    *   **Reduced Contrast**

ASSIGNMENT 3
"""

gamma_image = cv2.imread('gamma.jpg')

def gamma_correction(image, gamma):
    normalized_image = image.astype(np.float32) / 255.0
    gamma_corrected_image = np.power(normalized_image, gamma)
    gamma_corrected_image = (gamma_corrected_image * 255).astype(np.uint8)
    return gamma_corrected_image

print("Gamma correction function defined.")

gamma_values = [0.5, 1.0, 2.0]
gamma_corrected_images = {}

for gamma in gamma_values:
    gamma_corrected_images[gamma] = gamma_correction(gamma_image, gamma)
    print(f"Image gamma corrected with gamma={gamma}")

print("Gamma corrections applied for all specified values.")

plt.figure(figsize=(15, 5))

plt.subplot(1, len(gamma_values) + 1, 1)
plt.imshow(cv2.cvtColor(gamma_image, cv2.COLOR_BGR2RGB))
plt.title('Original Image')
plt.axis('off')

for i, gamma in enumerate(gamma_values):
    plt.subplot(1, len(gamma_values) + 1, i + 2)
    plt.imshow(cv2.cvtColor(gamma_corrected_images[gamma], cv2.COLOR_BGR2RGB))
    plt.title(f'Gamma = {gamma}')
    plt.axis('off')

plt.tight_layout()
plt.show()
print("Original and gamma-corrected images displayed.")

"""**Reasoning**:
I need to generate and display plots of the intensity mapping curves for each applied gamma value to visually represent how the input pixel intensities are mapped to output intensities for different gamma values. This will help in understanding the gamma correction process more deeply.


"""

def plot_intensity_mapping_curve(gamma, ax):
    r = np.linspace(0, 255, 256)
    normalized_r = r / 255.0
    s = np.power(normalized_r, gamma)
    scaled_s = s * 255

    ax.plot(r, scaled_s, color='blue', linewidth=2)
    ax.set_title(f'Intensity Mapping Curve (Gamma = {gamma})')
    ax.set_xlabel('Input Intensity (r)')
    ax.set_ylabel('Output Intensity (s)')
    ax.set_xlim([0, 255])
    ax.set_ylim([0, 255])
    ax.grid(True)
    ax.set_aspect('equal', adjustable='box')

plt.figure(figsize=(15, 5))

for i, gamma in enumerate(gamma_values):
    ax = plt.subplot(1, len(gamma_values), i + 1)
    plot_intensity_mapping_curve(gamma, ax)

plt.tight_layout()
plt.show()
print("Intensity mapping curves displayed for all specified gamma values.")

"""### Q&A

1.  **Which gamma values make the image brighter?**
    Gamma values less than 1 (e.g., 0.5) make the image brighter.
2.  **How does gamma correction relate to human vision?**
    Gamma correction accounts for the non-linear way the human visual system perceives brightness, where sensitivity to changes is higher in darker regions than in brighter ones.

ASSIGNMENT 4
"""

grayscale_comparison_image_path = 'grayscale_image_new.jpg'
grayscale_comparison_image = cv2.imread(grayscale_comparison_image_path, cv2.IMREAD_GRAYSCALE)

negative_image = 255 - grayscale_comparison_image

def log_transform_comparison(image, c):
    image_float = image.astype(np.float32)
    transformed_image = c * np.log(1 + image_float)
    transformed_image = cv2.normalize(transformed_image, None, 0, 255, cv2.NORM_MINMAX)
    return transformed_image.astype(np.uint8)

def gamma_correction_comparison(image, gamma):
    normalized_image = image.astype(np.float32) / 255.0
    gamma_corrected_image = np.power(normalized_image, gamma)
    gamma_corrected_image = (gamma_corrected_image * 255).astype(np.uint8)
    return gamma_corrected_image

c_log = 30
gamma_val1 = 0.5
gamma_val2 = 2.0

log_transformed_image = log_transform_comparison(grayscale_comparison_image, c_log)
gamma_corrected_image_0_5 = gamma_correction_comparison(grayscale_comparison_image, gamma_val1)
gamma_corrected_image_2_0 = gamma_correction_comparison(grayscale_comparison_image, gamma_val2)

plt.figure(figsize=(18, 6))

plt.subplot(1, 5, 1)
plt.imshow(grayscale_comparison_image, cmap='gray')
plt.title('Original Grayscale')
plt.axis('off')

plt.subplot(1, 5, 2)
plt.imshow(negative_image, cmap='gray')
plt.title('Negative Transform')
plt.axis('off')

plt.subplot(1, 5, 3)
plt.imshow(log_transformed_image, cmap='gray')
plt.title(f'Log Transform (c={c_log})')
plt.axis('off')

plt.subplot(1, 5, 4)
plt.imshow(gamma_corrected_image_0_5, cmap='gray')
plt.title(f'Gamma Corrected (γ={gamma_val1})')
plt.axis('off')

plt.subplot(1, 5, 5)
plt.imshow(gamma_corrected_image_2_0, cmap='gray')
plt.title(f'Gamma Corrected (γ={gamma_val2})')
plt.axis('off')

plt.tight_layout()
plt.show()

"""### Questions:

1.  **Which method improves visibility the most?**
    The **Log Transform** (with c=30 in the example) generally improves visibility the most, especially in darker regions.

2.  **Which transformation distorts the image the most?**
Gamma Correction (especially with extreme values like γ=0.5 or γ=2.0) tends to visually distort the image the most from its original appearance.

ASSIGNMENT 5
"""

negative_image_hist = 255 - grayscale_comparison_image
log_transformed_image_hist = log_transform_comparison(grayscale_comparison_image, c_log)
gamma_corrected_image_0_5_hist = gamma_correction_comparison(grayscale_comparison_image, gamma_val1)
gamma_corrected_image_2_0_hist = gamma_correction_comparison(grayscale_comparison_image, gamma_val2)

print("Transformed images (negative, log, gamma 0.5, gamma 2.0) have been prepared for histogram plotting.")

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(grayscale_comparison_image, cmap='gray')
plt.title('Original Grayscale Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plot_histogram(grayscale_comparison_image, 'Histogram - Original Grayscale', plt.gca())

plt.tight_layout()
plt.show()

print("Original grayscale image and its histogram displayed.")

plt.figure(figsize=(15, 20))

images_to_plot = {
    'Negative Transform': negative_image_hist,
    'Log Transform (c=30)': log_transformed_image_hist,
    'Gamma Corrected (γ=0.5)': gamma_corrected_image_0_5_hist,
    'Gamma Corrected (γ=2.0)': gamma_corrected_image_2_0_hist
}

plot_index = 1
for title, img in images_to_plot.items():
    plt.subplot(len(images_to_plot), 2, plot_index)
    plt.imshow(img, cmap='gray')
    plt.title(title)
    plt.axis('off')
    plot_index += 1

    plt.subplot(len(images_to_plot), 2, plot_index)
    plot_histogram(img, f'Histogram - {title}', plt.gca())
    plot_index += 1

plt.tight_layout()
plt.show()

print("Transformed images and their histograms displayed.")

equalized_grayscale_image = cv2.equalizeHist(grayscale_comparison_image)

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(equalized_grayscale_image, cmap='gray')
plt.title('Histogram Equalized Grayscale Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plot_histogram(equalized_grayscale_image, 'Histogram - Equalized Grayscale', plt.gca())

plt.tight_layout()
plt.show()

print("Histogram equalized image and its histogram displayed.")

"""BONUS"""

negative_equalized_image = 255 - equalized_grayscale_image
log_transformed_equalized_image = log_transform_comparison(equalized_grayscale_image, c_log)
gamma_corrected_equalized_image_0_5 = gamma_correction_comparison(equalized_grayscale_image, gamma_val1)
gamma_corrected_equalized_image_2_0 = gamma_correction_comparison(equalized_grayscale_image, gamma_val2)

print("Transformed equalized images (negative, log, gamma 0.5, gamma 2.0) have been prepared.")

plt.figure(figsize=(15, 20))

equalized_images_to_plot = {
    'Negative Equalized': negative_equalized_image,
    'Log Transformed Equalized (c=30)': log_transformed_equalized_image,
    'Gamma Corrected Equalized (γ=0.5)': gamma_corrected_equalized_image_0_5,
    'Gamma Corrected Equalized (γ=2.0)': gamma_corrected_equalized_image_2_0
}

plot_index = 1
for title, img in equalized_images_to_plot.items():
    plt.subplot(len(equalized_images_to_plot), 2, plot_index)
    plt.imshow(img, cmap='gray')
    plt.title(title)
    plt.axis('off')
    plot_index += 1

    plt.subplot(len(equalized_images_to_plot), 2, plot_index)
    plot_histogram(img, f'Histogram - {title}', plt.gca())
    plot_index += 1

plt.tight_layout()
plt.show()

print("Transformed equalized images and their histograms displayed.")

"""ASSINGMENT 6"""

dark_color_image = cv2.imread(dark_img_path)

dark_color_image_rgb = cv2.cvtColor(dark_color_image, cv2.COLOR_BGR2RGB)

def gamma_correction_color(image, gamma):
    normalized_image = image.astype(np.float32) / 255.0
    gamma_corrected_image = np.power(normalized_image, gamma)
    gamma_corrected_image = (gamma_corrected_image * 255).astype(np.uint8)
    return gamma_corrected_image

gamma_val = 2.2
gamma_corrected_rgb = gamma_correction_color(dark_color_image_rgb, gamma_val)

dark_color_image_hsv = cv2.cvtColor(dark_color_image, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(dark_color_image_hsv)

gamma_corrected_v = gamma_correction(v, gamma_val)

merged_hsv = cv2.merge([h, s, gamma_corrected_v])
gamma_corrected_hsv_rgb = cv2.cvtColor(merged_hsv, cv2.COLOR_HSV2RGB)

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(dark_color_image_rgb)
plt.title('Original Color Image (RGB)')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(gamma_corrected_rgb)
plt.title(f'Gamma Corrected (RGB, γ={gamma_val})')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(gamma_corrected_hsv_rgb)
plt.title(f'Gamma Corrected (HSV-V only, γ={gamma_val})')
plt.axis('off')

plt.tight_layout()
plt.show()

print("Original, RGB gamma-corrected, and HSV intensity-corrected images displayed for comparison.")

"""### Q&A

1.  **What color distortion is observed with direct RGB gamma correction?**
    When gamma correction is applied directly to the RGB channels, the image becomes significantly brighter. However, it often leads to a noticeable color shift or an unnatural hue.
2.  **Which color space is more suitable for brightness enhancement without color distortion, and why?**
    The HSV color space is highly suitable for brightness adjustments like gamma correction when the goal is to avoid color distortion. T

ASSIGNMENT 7
"""

medical_image_gray = cv2.imread('medical.jpg', cv2.IMREAD_GRAYSCALE)
landscape_image_gray = cv2.imread('landscape.jpg', cv2.IMREAD_GRAYSCALE)

print("Medical and landscape images loaded as grayscale.")

def intensity_slice_gray(image, lower_bound, upper_bound):
    sliced_image = np.full(image.shape, 128, dtype=np.uint8)
    mask = (image >= lower_bound) & (image <= upper_bound)
    sliced_image[mask] = image[mask]
    return sliced_image

def intensity_slice_black_white(image, lower_bound, upper_bound):
    sliced_image = np.zeros(image.shape, dtype=np.uint8)
    mask_in_range = (image >= lower_bound) & (image <= upper_bound)
    mask_out_of_range = ~mask_in_range

    sliced_image[mask_in_range] = image[mask_in_range]
    sliced_image[mask_out_of_range] = 255 # Set outside range to white
    return sliced_image

print("Intensity slicing functions defined: intensity_slice_gray and intensity_slice_black_white.")

lower_bound_medical = 50
upper_bound_medical = 100

medical_sliced_gray = intensity_slice_gray(medical_image_gray, lower_bound_medical, upper_bound_medical)
medical_sliced_black_white = intensity_slice_black_white(medical_image_gray, lower_bound_medical, upper_bound_medical)

print("Intensity slicing applied to medical image using both methods.")

lower_bound_landscape = 150
upper_bound_landscape = 220

landscape_sliced_gray = intensity_slice_gray(landscape_image_gray, lower_bound_landscape, upper_bound_landscape)
landscape_sliced_black_white = intensity_slice_black_white(landscape_image_gray, lower_bound_landscape, upper_bound_landscape)

print("Intensity slicing applied to landscape image using both methods.")

plt.figure(figsize=(15, 12))

plt.subplot(2, 3, 1)
plt.imshow(medical_image_gray, cmap='gray')
plt.title('Original Medical Image')
plt.axis('off')

plt.subplot(2, 3, 2)
plt.imshow(medical_sliced_gray, cmap='gray')
plt.title(f'Medical Sliced (Gray, {lower_bound_medical}-{upper_bound_medical})')
plt.axis('off')

plt.subplot(2, 3, 3)
plt.imshow(medical_sliced_black_white, cmap='gray')
plt.title(f'Medical Sliced (B/W, {lower_bound_medical}-{upper_bound_medical})')
plt.axis('off')

plt.subplot(2, 3, 4)
plt.imshow(landscape_image_gray, cmap='gray')
plt.title('Original Landscape Image')
plt.axis('off')

plt.subplot(2, 3, 5)
plt.imshow(landscape_sliced_gray, cmap='gray')
plt.title(f'Landscape Sliced (Gray, {lower_bound_landscape}-{upper_bound_landscape})')
plt.axis('off')

plt.subplot(2, 3, 6)
plt.imshow(landscape_sliced_black_white, cmap='gray')
plt.title(f'Landscape Sliced (B/W, {lower_bound_landscape}-{upper_bound_landscape})')
plt.axis('off')

plt.tight_layout()
plt.show()

print("Original and intensity sliced images displayed for medical and landscape.")

"""### Q&A

1.  **What happens to image detail outside the highlighted range?**
    When intensity slicing is applied, image details outside the specified intensity range are either suppressed to a uniform gray level.

2.  **How would you choose the intensity range to highlight for a specific application?**
    By analyzing the image's histogram for peaks or clusters corresponding to dominant intensity levels.l.

3.  **Compare this approach with simple thresholding.**
    Simple thresholding uses a single intensity value as a cutoff, producing a binary image. In contrast, intensity slicing uses a range of intensity values.

ASSIGNMENT 8
"""

low_light_grayscale_image = cv2.imread('low_light_image.jpg', cv2.IMREAD_GRAYSCALE)

def contrast_stretching(image):
    min_val = np.min(image)
    max_val = np.max(image)

    if max_val - min_val == 0:
        return np.zeros_like(image, dtype=np.uint8)

    stretched_image = ((image - min_val) / (max_val - min_val)) * 255
    return stretched_image.astype(np.uint8)

c_log = 30
gamma_val1 = 0.5
gamma_val2 = 2.0

negative_transformed_image = 255 - low_light_grayscale_image
log_transformed_image = log_transform_comparison(low_light_grayscale_image, c_log)
contrast_stretched_image = contrast_stretching(low_light_grayscale_image)
gamma_0_5_image = gamma_correction_comparison(low_light_grayscale_image, gamma_val1)
gamma_2_0_image = gamma_correction_comparison(low_light_grayscale_image, gamma_val2)

log_then_contrast_stretch = contrast_stretching(log_transformed_image)
gamma_0_5_then_negative = 255 - gamma_0_5_image
negative_then_gamma_2_0 = gamma_correction_comparison(negative_transformed_image, gamma_val2)

print("All individual and sequenced transformations have been applied to the low-light grayscale image.")

plt.figure(figsize=(18, 18))

images_to_display = {
    'Original Image': low_light_grayscale_image,
    'Negative Transform': negative_transformed_image,
    'Log Transform (c=30)': log_transformed_image,
    'Contrast Stretched': contrast_stretched_image,
    'Gamma Corrected (γ=0.5)': gamma_0_5_image,
    'Gamma Corrected (γ=2.0)': gamma_2_0_image,
    'Log then Contrast Stretch': log_then_contrast_stretch,
    'Gamma 0.5 then Negative': gamma_0_5_then_negative,
    'Negative then Gamma 2.0': negative_then_gamma_2_0
}

plot_index = 1
for title, img in images_to_display.items():
    plt.subplot(3, 3, plot_index)
    plt.imshow(img, cmap='gray')
    plt.title(title)
    plt.axis('off')
    plot_index += 1

plt.tight_layout()
plt.show()

print("All original and transformed images displayed for comparison.")

"""## Q&A:

1.  **Does the order of transformations matter?**
    Yes, the order of transformations significantly matters. This can be observed by comparing the sequenced transformations:
    *   **'Gamma 0.5 then Negative' vs. 'Negative then Gamma 2.0':**
        *   'Gamma 0.5 then Negative' applies a brightening gamma correction first (making the image brighter), then negates it. This results in an image where previously dark areas (now brighter due to gamma) become darker, and bright areas (now even brighter) become very dark or black.
        *   'Negative then Gamma 2.0' negates the image first (making dark areas bright and vice versa), then applies a darkening gamma correction (gamma > 1). This results in an image where the already brightened dark areas from the negative transform are then further compressed towards darker tones, and the original bright areas (now dark) become even darker.

2.  **Which individual transformation or combination of transformations provides the most significant enhancement of details and overall visibility in the low-light image?**
    From the visual comparison, the **'Log Transform (c=30)'** alone seems to provide the most significant enhancement of details and overall visibility for this low-light image.

3.  **Do these operations possess commutative or associative properties?**
    Based on the visual comparisons, these image processing operations (negative, log, gamma correction, contrast stretching) generally **do not possess commutative or associative properties**.

ASSIGNMENT 9
"""

import cv2
from skimage.util import random_noise

clean_image_gray = cv2.imread('grayscale_image_new.jpg', cv2.IMREAD_GRAYSCALE)

def add_gaussian_noise(image):
    image_float = image.astype(float) / 255.0
    noisy_image = random_noise(image_float, mode='gaussian', var=0.01)
    noisy_image = (noisy_image * 255).astype(np.uint8)
    return noisy_image

def add_salt_pepper_noise(image):
    image_float = image.astype(float) / 255.0
    noisy_image = random_noise(image_float, mode='s&p', amount=0.05)
    noisy_image = (noisy_image * 255).astype(np.uint8)
    return noisy_image

print("Grayscale image loaded and noise functions defined.")

gaussian_noisy_image = add_gaussian_noise(clean_image_gray)
salt_pepper_noisy_image = add_salt_pepper_noise(clean_image_gray)

print("Gaussian and Salt-and-pepper noisy images generated.")

negative_gaussian_image = 255 - gaussian_noisy_image
log_gaussian_image = log_transform_comparison(gaussian_noisy_image, c_log)
gamma_0_5_gaussian_image = gamma_correction_comparison(gaussian_noisy_image, gamma_val1)
gamma_2_0_gaussian_image = gamma_correction_comparison(gaussian_noisy_image, gamma_val2)

print("Negative, log, and gamma transformations applied to the Gaussian noisy image.")

negative_salt_pepper_image = 255 - salt_pepper_noisy_image
log_salt_pepper_image = log_transform_comparison(salt_pepper_noisy_image, c_log)
gamma_0_5_salt_pepper_image = gamma_correction_comparison(salt_pepper_noisy_image, gamma_val1)
gamma_2_0_salt_pepper_image = gamma_correction_comparison(salt_pepper_noisy_image, gamma_val2)

print("Negative, log, and gamma transformations applied to the Salt-and-pepper noisy image.")

plt.figure(figsize=(15, 25))

images_gaussian_to_plot = {
    'Original Gaussian Noisy': gaussian_noisy_image,
    'Negative Gaussian': negative_gaussian_image,
    'Log Transformed Gaussian (c=30)': log_gaussian_image,
    'Gamma Corrected Gaussian (γ=0.5)': gamma_0_5_gaussian_image,
    'Gamma Corrected Gaussian (γ=2.0)': gamma_2_0_gaussian_image
}

plot_index = 1
for title, img in images_gaussian_to_plot.items():
    plt.subplot(len(images_gaussian_to_plot), 2, plot_index)
    plt.imshow(img, cmap='gray')
    plt.title(title)
    plt.axis('off')
    plot_index += 1

    plt.subplot(len(images_gaussian_to_plot), 2, plot_index)
    plot_histogram(img, f'Histogram - {title}', plt.gca())
    plot_index += 1

plt.tight_layout()
plt.show()

print("Gaussian noisy image and its transformations, along with their histograms, displayed.")

plt.figure(figsize=(15, 25))

images_salt_pepper_to_plot = {
    'Original Salt-and-pepper Noisy': salt_pepper_noisy_image,
    'Negative Salt-and-pepper': negative_salt_pepper_image,
    'Log Transformed Salt-and-pepper (c=30)': log_salt_pepper_image,
    'Gamma Corrected Salt-and-pepper (γ=0.5)': gamma_0_5_salt_pepper_image,
    'Gamma Corrected Salt-and-pepper (γ=2.0)': gamma_2_0_salt_pepper_image
}

plot_index = 1
for title, img in images_salt_pepper_to_plot.items():
    plt.subplot(len(images_salt_pepper_to_plot), 2, plot_index)
    plt.imshow(img, cmap='gray')
    plt.title(title)
    plt.axis('off')
    plot_index += 1

    plt.subplot(len(images_salt_pepper_to_plot), 2, plot_index)
    plot_histogram(img, f'Histogram - {title}', plt.gca())
    plot_index += 1

plt.tight_layout()
plt.show()

print("Salt-and-pepper noisy image and its transformations, along with their histograms, displayed.")

"""## Summary:

### Q&A

1.  **Which transformations amplify noise? Which suppress it?**
    Most intensity transformations tend to amplify or make noise more apparent rather than suppress it.

2.  **Why does negative transformation make salt-and-pepper noise more visible?**
    Negative transformation makes salt-and-pepper noise more visible because it inverts extreme pixel values.

3.  **Should noise reduction be applied before or after intensity transformation?**
    Noise reduction should generally be applied *before* intensity transformations. This is because intensity transformations can amplify existing noise or alter its characteristics, making subsequent noise reduction more difficult or less effective.

ASSIGNMENT 10
"""

import cv2
import numpy as np

original_gray_image = cv2.imread('grayscale_image_new.jpg', cv2.IMREAD_GRAYSCALE)

def reduce_bit_depth(image, bits):
    levels = 2 ** bits
    scaling_factor = 256 / levels
    reduced_image = np.round(image / scaling_factor) * scaling_factor
    reduced_image = np.clip(reduced_image, 0, 255).astype(np.uint8)
    return reduced_image

c_log = 30
gamma_val1 = 0.5

negative_transformed_original = 255 - original_gray_image
log_transformed_original = log_transform_comparison(original_gray_image, c_log)
gamma_corrected_original_0_5 = gamma_correction_comparison(original_gray_image, gamma_val1)

print("Original image transformed with Negative, Log, and Gamma 0.5 transformations.")

bit_depths = [4, 3, 2]

transformed_images_bit_reduced = {
    'Negative_Original': {},
    'Log_Original': {},
    'Gamma05_Original': {}
}

for bits in bit_depths:
    transformed_images_bit_reduced['Negative_Original'][f'{bits}_bits'] = reduce_bit_depth(negative_transformed_original, bits)
    transformed_images_bit_reduced['Log_Original'][f'{bits}_bits'] = reduce_bit_depth(log_transformed_original, bits)
    transformed_images_bit_reduced['Gamma05_Original'][f'{bits}_bits'] = reduce_bit_depth(gamma_corrected_original_0_5, bits)

print("Bit-depth reduction applied to all transformed original images for 4, 3, and 2 bits.")

plt.figure(figsize=(18, 25))

plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, 1)
plt.imshow(original_gray_image, cmap='gray')
plt.title('Original Grayscale Image')
plt.axis('off')

plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, 2)
plot_histogram(original_gray_image, 'Histogram - Original Grayscale', plt.gca())
plot_index = 3

plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, plot_index)
plt.imshow(negative_transformed_original, cmap='gray')
plt.title('Negative Transformed Original')
plt.axis('off')
plot_index += 1
plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, plot_index)
plot_histogram(negative_transformed_original, 'Histogram - Negative Transformed', plt.gca())
plot_index += 1

plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, plot_index)
plt.imshow(log_transformed_original, cmap='gray')
plt.title(f'Log Transformed Original (c={c_log})')
plt.axis('off')
plot_index += 1
plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, plot_index)
plot_histogram(log_transformed_original, f'Histogram - Log Transformed (c={c_log})', plt.gca())
plot_index += 1

plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, plot_index)
plt.imshow(gamma_corrected_original_0_5, cmap='gray')
plt.title(f'Gamma Corrected Original (γ={gamma_val1})')
plt.axis('off')
plot_index += 1
plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, plot_index)
plot_histogram(gamma_corrected_original_0_5, f'Histogram - Gamma Corrected (γ={gamma_val1})', plt.gca())
plot_index += 1

for transform_name, bit_images in transformed_images_bit_reduced.items():
    for bits_str, img in bit_images.items():
        plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, plot_index)
        plt.imshow(img, cmap='gray')
        plt.title(f'{transform_name.replace("_", " ")} - {bits_str}')
        plt.axis('off')
        plot_index += 1

        plt.subplot(len(transformed_images_bit_reduced) * len(bit_depths) + 4, 2, plot_index)
        plot_histogram(img, f'Histogram - {transform_name.replace("_", " ")} - {bits_str}', plt.gca())
        plot_index += 1

plt.tight_layout()
plt.show()

print("Original, transformed, and bit-depth reduced images with their histograms displayed.")

bit_depths = [4, 3, 2]

original_bit_reduced = {}
for bits in bit_depths:
    original_bit_reduced[f'{bits}_bits'] = reduce_bit_depth(original_gray_image, bits)

bit_reduced_then_transformed_images = {
    'Negative': {},
    'Log': {},
    'Gamma05': {}
}

for bits_str, img_reduced in original_bit_reduced.items():
    bit_reduced_then_transformed_images['Negative'][bits_str] = 255 - img_reduced
    bit_reduced_then_transformed_images['Log'][bits_str] = log_transform_comparison(img_reduced, c_log)
    bit_reduced_then_transformed_images['Gamma05'][bits_str] = gamma_correction_comparison(img_reduced, gamma_val1)

print("Bit-depth reduction applied to original image, followed by Negative, Log, and Gamma 0.5 transformations for each bit-reduced version.")

plt.figure(figsize=(15, 25))

plot_index = 1
for transform_type, bit_reduced_images in bit_reduced_then_transformed_images.items():
    for bits_str, img in bit_reduced_images.items():
        plt.subplot(len(bit_reduced_then_transformed_images) * len(bit_depths), 2, plot_index)
        plt.imshow(img, cmap='gray')
        plt.title(f'{transform_type} after {bits_str} Reduction')
        plt.axis('off')
        plot_index += 1

        plt.subplot(len(bit_reduced_then_transformed_images) * len(bit_depths), 2, plot_index)
        plot_histogram(img, f'Histogram - {transform_type} after {bits_str} Reduction', plt.gca())
        plot_index += 1

plt.tight_layout()
plt.show()

print("Bit-reduced then transformed images and their histograms displayed.")

plt.figure(figsize=(15, 75))

plot_index = 1

plt.subplot(25, 2, plot_index)
plt.imshow(original_gray_image, cmap='gray')
plt.title('Original Grayscale Image')
plt.axis('off')
plot_index += 1

plt.subplot(25, 2, plot_index)
plot_histogram(original_gray_image, 'Histogram - Original Grayscale', plt.gca())
plot_index += 1
for bits_str, img in original_bit_reduced.items():
    plt.subplot(25, 2, plot_index)
    plt.imshow(img, cmap='gray')
    plt.title(f'Original Reduced to {bits_str}')
    plt.axis('off')
    plot_index += 1

    plt.subplot(25, 2, plot_index)
    plot_histogram(img, f'Histogram - Original Reduced to {bits_str}', plt.gca())
    plot_index += 1
images_transformed_original = {
    'Negative Transformed Original': negative_transformed_original,
    f'Log Transformed Original (c={c_log})': log_transformed_original,
    f'Gamma Corrected Original (γ={gamma_val1})': gamma_corrected_original_0_5
}

for title, img in images_transformed_original.items():
    plt.subplot(25, 2, plot_index)
    plt.imshow(img, cmap='gray')
    plt.title(title)
    plt.axis('off')
    plot_index += 1

    plt.subplot(25, 2, plot_index)
    plot_histogram(img, f'Histogram - {title}', plt.gca())
    plot_index += 1
for transform_name, bit_images in transformed_images_bit_reduced.items():
    for bits_str, img in bit_images.items():
        plt.subplot(25, 2, plot_index)
        plt.imshow(img, cmap='gray')
        plt.title(f'{transform_name.replace("_", " ")} - {bits_str}')
        plt.axis('off')
        plot_index += 1

        plt.subplot(25, 2, plot_index)
        plot_histogram(img, f'Histogram - {transform_name.replace("_", " ")} - {bits_str}', plt.gca())
        plot_index += 1

for transform_type, bit_reduced_images in bit_reduced_then_transformed_images.items():
    for bits_str, img in bit_reduced_images.items():
        plt.subplot(25, 2, plot_index)
        plt.imshow(img, cmap='gray')
        plt.title(f'{transform_type} after {bits_str} Reduction')
        plt.axis('off')
        plot_index += 1

        plt.subplot(25, 2, plot_index)
        plot_histogram(img, f'Histogram - {transform_type} after {bits_str} Reduction', plt.gca())
        plot_index += 1

plt.tight_layout()
plt.show()

print("Comprehensive visualization of original, transformed, and bit-depth reduced images with histograms displayed.")

"""### Q&A

1.  **Why does banding occur after bit-depth reduction?**
    Banding, or contouring, occurs because reducing the bit-depth significantly reduces the number of available intensity levels.

2.  **Which transformations minimize banding artifacts?**
    Generally, none of the tested transformations (Negative, Log, Gamma Correction) effectively minimize existing banding artifacts once they have been introduced by bit-depth reduction.

3.  **What is the minimum bit-depth needed for acceptable visual quality?**
    For the `grayscale_image_new.jpg` used in the analysis, **4 bits** represents a subjective threshold for acceptable visual quality.

ASSIGNMENT 11
"""

landscape_image_assign11 = cv2.imread('landscape.jpg', cv2.IMREAD_GRAYSCALE)

def calculate_average_intensity(image):
    return np.mean(image)

def calculate_contrast(image):
    return np.std(image)

def calculate_entropy(image):
    hist = cv2.calcHist([image], [0], None, [256], [0, 256])
    hist = hist.ravel() / hist.sum()
    probabilities = hist[hist > 0]
    entropy = -np.sum(probabilities * np.log2(probabilities))
    return entropy

print("Image 'landscape.jpg' loaded and metric calculation functions defined (average intensity, contrast, entropy).")

gamma_values = [0.2, 0.5, 1.0, 1.5, 2.5]
gamma_results = []

for gamma_val in gamma_values:
    corrected_image = gamma_correction(landscape_image_assign11, gamma_val)
    avg_intensity = calculate_average_intensity(corrected_image)
    contrast = calculate_contrast(corrected_image)
    entropy = calculate_entropy(corrected_image)

    gamma_results.append({
        'gamma': gamma_val,
        'average_intensity': avg_intensity,
        'contrast': contrast,
        'entropy': entropy
    })

print("Gamma correction applied and metrics calculated for all specified gamma values:")
for result in gamma_results:
    print(result)

c_values_log = [5, 10, 30, 60, 100]
log_results = []

for c_val in c_values_log:
    transformed_image = log_transform(landscape_image_assign11, c_val)
    avg_intensity = calculate_average_intensity(transformed_image)
    contrast = calculate_contrast(transformed_image)
    entropy = calculate_entropy(transformed_image)

    log_results.append({
        'c_value': c_val,
        'average_intensity': avg_intensity,
        'contrast': contrast,
        'entropy': entropy
    })

print("Log transformation applied and metrics calculated for all specified c values:")
for result in log_results:
    print(result)

plt.figure(figsize=(18, 12))

gammas = [result['gamma'] for result in gamma_results]
gamma_avg_intensities = [result['average_intensity'] for result in gamma_results]
gamma_contrasts = [result['contrast'] for result in gamma_results]
gamma_entropies = [result['entropy'] for result in gamma_results]

plt.subplot(2, 3, 1)
plt.plot(gammas, gamma_avg_intensities, marker='o')
plt.title('Gamma vs. Average Intensity')
plt.xlabel('Gamma Value')
plt.ylabel('Average Intensity')
plt.grid(True)

plt.subplot(2, 3, 2)
plt.plot(gammas, gamma_contrasts, marker='o')
plt.title('Gamma vs. Contrast')
plt.xlabel('Gamma Value')
plt.ylabel('Contrast (Standard Deviation)')
plt.grid(True)

plt.subplot(2, 3, 3)
plt.plot(gammas, gamma_entropies, marker='o')
plt.title('Gamma vs. Entropy')
plt.xlabel('Gamma Value')
plt.ylabel('Entropy')
plt.grid(True)

c_values_log_plot = [result['c_value'] for result in log_results]
log_avg_intensities = [result['average_intensity'] for result in log_results]
log_contrasts = [result['contrast'] for result in log_results]
log_entropies = [result['entropy'] for result in log_results]

plt.subplot(2, 3, 4)
plt.plot(c_values_log_plot, log_avg_intensities, marker='o')
plt.title('C Value vs. Average Intensity (Log Transform)')
plt.xlabel('C Value')
plt.ylabel('Average Intensity')
plt.grid(True)

plt.subplot(2, 3, 5)
plt.plot(c_values_log_plot, log_contrasts, marker='o')
plt.title('C Value vs. Contrast (Log Transform)')
plt.xlabel('C Value')
plt.ylabel('Contrast (Standard Deviation)')
plt.grid(True)

plt.subplot(2, 3, 6)
plt.plot(c_values_log_plot, log_entropies, marker='o')
plt.title('C Value vs. Entropy (Log Transform)')
plt.xlabel('C Value')
plt.ylabel('Entropy')
plt.grid(True)

plt.tight_layout()
plt.show()

print("Plots showing metrics vs. parameter values displayed.")

"""### Q&A

1.  **Which parameter gives maximum contrast? Maximum entropy?**
    *   **Gamma Correction:** For the `landscape.jpg` image, a gamma value of 1.0 yielded both the maximum contrast (46.46) and maximum entropy (7.44).
    *   **Log Transformation:** For log transformation, `c_values` of 5, 10, 30, 60, and 100 all resulted in similar maximum contrast values around 25.42. Similarly, `c_values` of 5, 10, and 100 provided the highest entropy values at approximately 6.512.

2.  **Is there a single 'best' parameter for all images?**
    No, there is generally no single 'best' parameter for all images or enhancement goals. The optimal parameters are highly dependent on the image's inherent characteristics, the specific enhancement objective, and subjective human perception.

3.  **How would you automate parameter selection?**
    Automating parameter selection would involve:
    *   Defining objective quantitative metrics (e.g., average intensity for brightness, standard deviation for contrast, entropy for information content, edge detection quality) that align with desired visual outcomes.
    *   Employing an iterative search process across a defined parameter space, using optimization algorithms (like genetic algorithms or grid search) to find parameters that optimize a cost function based on these metrics.

ASSIGNMENT 12
"""

import cv2
import numpy as np

original_grayscale_image = cv2.imread('grayscale_image_new.jpg', cv2.IMREAD_GRAYSCALE)
print("Grayscale image loaded successfully.")

fixed_threshold_value = 128
ret, binary_fixed_threshold_image = cv2.threshold(original_grayscale_image, fixed_threshold_value, 255, cv2.THRESH_BINARY)
print(f"Fixed thresholding applied at {fixed_threshold_value}.")

ret_otsu, binary_otsu_image = cv2.threshold(original_grayscale_image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
print(f"Otsu's thresholding applied. Optimal threshold: {ret_otsu}")

import cv2
import numpy as np

kernel = np.ones((3,3),np.uint8)

negative_fixed_threshold_image = 255 - binary_fixed_threshold_image
eroded_fixed_threshold_image = cv2.erode(binary_fixed_threshold_image, kernel, iterations = 1)
dilated_fixed_threshold_image = cv2.dilate(binary_fixed_threshold_image, kernel, iterations = 1)

print("Transformations applied to fixed threshold binary image.")

negative_otsu_image = 255 - binary_otsu_image
eroded_otsu_image = cv2.erode(binary_otsu_image, kernel, iterations = 1)
dilated_otsu_image = cv2.dilate(binary_otsu_image, kernel, iterations = 1)

print("Transformations applied to Otsu's binary image.")

import matplotlib.pyplot as plt

plt.figure(figsize=(18, 20))

plt.subplot(4, 4, 1)
plt.imshow(original_grayscale_image, cmap='gray')
plt.title('Original Grayscale Image')
plt.axis('off')

plt.subplot(4, 4, 2)
plt.imshow(binary_fixed_threshold_image, cmap='gray')
plt.title(f'Binary (Fixed Threshold={fixed_threshold_value})')
plt.axis('off')

plt.subplot(4, 4, 3)
plt.imshow(negative_fixed_threshold_image, cmap='gray')
plt.title('Negative Fixed Threshold')
plt.axis('off')

plt.subplot(4, 4, 4)
plt.imshow(eroded_fixed_threshold_image, cmap='gray')
plt.title('Eroded Fixed Threshold')
plt.axis('off')

plt.subplot(4, 4, 5)
plt.imshow(dilated_fixed_threshold_image, cmap='gray')
plt.title('Dilated Fixed Threshold')
plt.axis('off')

plt.subplot(4, 4, 6)
plt.imshow(binary_otsu_image, cmap='gray')
plt.title(f'Binary (Otsu Threshold={ret_otsu:.0f})')
plt.axis('off')

plt.subplot(4, 4, 7)
plt.imshow(negative_otsu_image, cmap='gray')
plt.title('Negative Otsu')
plt.axis('off')

plt.subplot(4, 4, 8)
plt.imshow(eroded_otsu_image, cmap='gray')
plt.title('Eroded Otsu')
plt.axis('off')

plt.subplot(4, 4, 9)
plt.imshow(dilated_otsu_image, cmap='gray')
plt.title('Dilated Otsu')
plt.axis('off')

plt.tight_layout()
plt.show()

print("All original, binary, and transformed images displayed.")

"""## Summary:

### Q&A
1.  **What information is lost in binary conversion?**
    A significant amount of information is lost, as all nuanced grayscale values (0-255) are reduced to just two (0 for black and 255 for white).

2.  **How does negative affect object/background relationships?**
    Negative transformation inverts the brightness values.

3.  **What practical applications use binary image operations?**
    Binary image operations are used in:
    *   **Document Analysis (OCR):** Isolating text from backgrounds.
    *   **Medical Imaging:** Segmenting specific structures like tumors or blood vessels.
"""