# -*- coding: utf-8 -*-
"""CVLab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVvlU0y9V1dxfC_TAIRbcmwiT42UdTaZ
"""

import cv2
import matplotlib.pyplot as plt

"""Reading and Displaying an Image"""

img = cv2.imread("/content/image.jpg")
plt.imshow(img)
plt.title("Flower image displayed")
plt.show()

"""Understanding Image Shape and Channels"""

print("Imaage shape: ", img.shape)
print("Data type:  ", img.dtype)

"""Splitting and visualizing channels"""

b,g,r = cv2.split(img)
plt.figure(figsize=(12,4))
plt.subplot(1,3,1)
plt.imshow(b,cmap='gray')
plt.title("Blue channel")
plt.subplot(1,3,2)
plt.imshow(g,cmap='gray')
plt.title("Green channel")
plt.subplot(1,3,3)
plt.imshow(r,cmap='gray')
plt.title("Red channel")
plt.show()

x,y = 150,500
pixel = img[y,x]
print("Pixel value at (150,500): ", pixel)

"""Modifying Pixel values"""

img_modified = img.copy()
img_modified[1207:1727, 320: 1520] = [255,255,255]
plt.imshow(img_modified)
plt.show()

plt.imshow(cv2.cvtColor(img_modified, cv2.COLOR_BGR2RGB))

"""Creating an Image from scratch"""

import numpy as np
blankimg = np.zeros((1024,1024,3), dtype=np.uint8)
blankimg[:] = 255,0,255
plt.imshow(blankimg)
plt.show()

"""Gray Scale Conversion"""

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plt.imshow(gray, cmap='gray')
plt.title("Gray image")
plt.show()

"""Assg Q1"""

x,y = 277, 390
pixel = img[y,x]
print("Pixel value at (277,390): ", pixel)

"""Assg Q2"""

img_modify = img.copy()
h, w, _ = img.shape

region = img_modify[0:h//2, 0:w]
grr = cv2.cvtColor(region, cv2.COLOR_BGR2GRAY)
gray_region_bgr = cv2.cvtColor(grr, cv2.COLOR_GRAY2BGR)
img_modify[0:h//2, 0:w] = gray_region_bgr

plt.imshow(cv2.cvtColor(img_modify, cv2.COLOR_BGR2RGB))
plt.show()

"""Assg Q3"""

hsv_image = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(hsv_image)

v = cv2.add(v, 150)

final_hsv = cv2.merge((h, s, v))
final_bgr = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)

plt.imshow(cv2.cvtColor(final_bgr, cv2.COLOR_BGR2RGB))

"""Assg Q4"""

center_x, center_y = blankimg.shape[1] // 2, blankimg.shape[0] // 2
square_size = 200
half_size = square_size // 2

start_x = center_x - half_size
end_x = center_x + half_size
start_y = center_y - half_size
end_y = center_y + half_size

blankimg[start_y:end_y, start_x:end_x] = [255, 0, 0]

plt.imshow(blankimg)
plt.title("Blank Image with Red Square")
plt.show()

"""Assg Q5"""

b, g, r = cv2.split(img)
swapped_img = cv2.merge([r, g, b])
plt.imshow(cv2.cvtColor(swapped_img, cv2.COLOR_BGR2RGB))
plt.title("Image with Red and Blue Channels Swapped")
plt.show()



"""### Q1"""

import cv2
import numpy as np

img = cv2.imread('landscape.jpg')

cv2.imwrite('output.png', img)

"""### Q2"""

height, width = img.shape[:2]

channels = img.shape[2] if len(img.shape) == 3 else 1

data_type = img.dtype

print(f"Dimensions: Height={height}, Width={width}")
print(f"Channels: {channels}")
print(f"Data Type: {data_type}")

"""### Q3"""

fixed_width, fixed_height = 300, 300
resized_img = cv2.resize(img, (fixed_width, fixed_height), interpolation=cv2.INTER_AREA)

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Original Image')

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(resized_img, cv2.COLOR_BGR2RGB))
plt.title(f'Resized Image ({fixed_width}x{fixed_height})')

plt.show()

"""### Q4"""

original_height, original_width = img.shape[:2]
print(f"Original Image Shape: {img.shape}")

scaled_height = int(original_height * 0.5)
scaled_width = int(original_width * 0.5)
scaled_img = cv2.resize(img, (scaled_width, scaled_height), interpolation=cv2.INTER_AREA)

print(f"Scaled Image Shape: {scaled_img.shape}")

"""### Q5"""

grayscale_img_q5 = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

print(f"Grayscale Image Shape: {grayscale_img_q5.shape}")

"""### Q6"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

reconverted_bgr_img = cv2.cvtColor(grayscale_img_q5, cv2.COLOR_GRAY2BGR)

plt.imshow(cv2.cvtColor(reconverted_bgr_img, cv2.COLOR_BGR2RGB))
plt.title('Re-converted Grayscale to BGR Image')
plt.show()

"""### Q7"""

grayscale_img_q7 = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

plt.hist(grayscale_img_q7.ravel(), 256, [0, 256])
plt.title('Pixel Intensity Distribution (Grayscale)')
plt.xlabel('Pixel Value')
plt.ylabel('Frequency')
plt.show()

"""### Q8"""

normalized_img = img.astype(np.float32)

normalized_img = normalized_img / 255.0

print(f"Maximum pixel value after normalization: {normalized_img.max()}")
print(f"Minimum pixel value after normalization: {normalized_img.min()}")

"""### Q9"""

negative_img = 255 - img

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Original Image')

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(negative_img, cv2.COLOR_BGR2RGB))
plt.title('Negative Image')

plt.show()

"""### Q10"""

grayscale_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, binary_img = cv2.threshold(grayscale_img, 127, 255, cv2.THRESH_BINARY)

plt.imshow(binary_img, cmap='gray')
plt.title('Binary Thresholded Image')
plt.show()